package com.rules
import wang.crispin.example.drools.model.Car

rule "test-drools7-older-than-60"
agenda-group "test-drools7"
    when
        $car:Car(person.age > 60)
    then
        $car.setDiscount(80);
        System.out.println("test-drools7-older-than-60: " + $car.getPerson().getAge());
end

rule "test-drools7-older-other"
    when
        $car:Car(person.age <= 60)
    then
        $car.setDiscount(90);
        System.out.println("test-drools7-older-other: " + $car.getPerson().getAge());
end
