package com.rhs;
import wang.crispin.example.drools.model.Person
dialect  "java"

rule "modify-demo-rule-1"
agenda-group "modify-demo"
    when
        $p : Person(age == 21)
    then
        System.out.println("trigger modify demo rule 1");
        modify($p){
            setAge(22),setName("Tom")
        }
end


rule "modify-demo-rule-2"
agenda-group "modify-demo"
    when
        $p : Person(age == 22)
    then
        System.out.println("trigger modify demo rule 2");
end
