package com.salienctTest;
import wang.crispin.example.drools.model.Person

rule "salience-1"
salience 2
    when
    then
        System.out.println(String.format("%s被执行了","salience-1"));
end

rule "salience-2"
salience 1
    when
    then
        System.out.println(String.format("%s被执行了","salience-2"));
end

rule "salience-3"
salience sal
    when
        $person : Person(sal : age)
    then
        System.out.println(String.format("%s被执行了","salience-3"));
end
